# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edledit/edledit.ui'
#
# Created: Sat Jul 16 10:56:41 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import QWidget, QGridLayout, QSizePolicy, QMenuBar, QMenu, QToolBar, QStatusBar, QAction, QApplication

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(714, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/edledit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.player = VideoPlayer(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player.sizePolicy().hasHeightForWidth())
        self.player.setSizePolicy(sizePolicy)
        self.player.setMinimumSize(QtCore.QSize(320, 180))
        self.player.setBaseSize(QtCore.QSize(640, 360))
        self.player.setObjectName(_fromUtf8("player"))
        self.gridLayout.addWidget(self.player, 0, 0, 1, 1)
        self.edlWidget = EDLWidget(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edlWidget.sizePolicy().hasHeightForWidth())
        self.edlWidget.setSizePolicy(sizePolicy)
        self.edlWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.edlWidget.setAutoFillBackground(True)
        self.edlWidget.setObjectName(_fromUtf8("edlWidget"))
        self.gridLayout.addWidget(self.edlWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menu_Go = QMenu(self.menubar)
        self.menu_Go.setObjectName(_fromUtf8("menu_Go"))
        self.menu_Edit = QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(16, 16))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSaveEDL = QAction(MainWindow)
        self.actionSaveEDL.setEnabled(False)
        self.actionSaveEDL.setObjectName(_fromUtf8("actionSaveEDL"))
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionSkipForward = QAction(MainWindow)
        self.actionSkipForward.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/control_fastforward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSkipForward.setIcon(icon1)
        self.actionSkipForward.setIconVisibleInMenu(True)
        self.actionSkipForward.setObjectName(_fromUtf8("actionSkipForward"))
        self.actionSkipBackwards = QAction(MainWindow)
        self.actionSkipBackwards.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/control_rewind.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSkipBackwards.setIcon(icon2)
        self.actionSkipBackwards.setIconVisibleInMenu(True)
        self.actionSkipBackwards.setObjectName(_fromUtf8("actionSkipBackwards"))
        self.actionPreviousCutBoundary = QAction(MainWindow)
        self.actionPreviousCutBoundary.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/control_start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreviousCutBoundary.setIcon(icon3)
        self.actionPreviousCutBoundary.setIconVisibleInMenu(True)
        self.actionPreviousCutBoundary.setObjectName(_fromUtf8("actionPreviousCutBoundary"))
        self.actionNextCutBoundary = QAction(MainWindow)
        self.actionNextCutBoundary.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/control_end.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNextCutBoundary.setIcon(icon4)
        self.actionNextCutBoundary.setIconVisibleInMenu(True)
        self.actionNextCutBoundary.setObjectName(_fromUtf8("actionNextCutBoundary"))
        self.actionPlayPause = QAction(MainWindow)
        self.actionPlayPause.setCheckable(True)
        self.actionPlayPause.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/control_play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/control_pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionPlayPause.setIcon(icon5)
        self.actionPlayPause.setIconVisibleInMenu(True)
        self.actionPlayPause.setObjectName(_fromUtf8("actionPlayPause"))
        self.actionStartCut = QAction(MainWindow)
        self.actionStartCut.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cut_start.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStartCut.setIcon(icon6)
        self.actionStartCut.setIconVisibleInMenu(True)
        self.actionStartCut.setObjectName(_fromUtf8("actionStartCut"))
        self.actionStopCut = QAction(MainWindow)
        self.actionStopCut.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cut_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStopCut.setIcon(icon7)
        self.actionStopCut.setIconVisibleInMenu(True)
        self.actionStopCut.setObjectName(_fromUtf8("actionStopCut"))
        self.actionDeleteCut = QAction(MainWindow)
        self.actionDeleteCut.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cross.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteCut.setIcon(icon8)
        self.actionDeleteCut.setIconVisibleInMenu(True)
        self.actionDeleteCut.setObjectName(_fromUtf8("actionDeleteCut"))
        self.actionIncreaseStep = QAction(MainWindow)
        self.actionIncreaseStep.setObjectName(_fromUtf8("actionIncreaseStep"))
        self.actionDecreaseStep = QAction(MainWindow)
        self.actionDecreaseStep.setObjectName(_fromUtf8("actionDecreaseStep"))
        self.actionDecreaseStepAndSkipForward = QAction(MainWindow)
        self.actionDecreaseStepAndSkipForward.setObjectName(_fromUtf8("actionDecreaseStepAndSkipForward"))
        self.actionDecreaseStepAndSkipBackwards = QAction(MainWindow)
        self.actionDecreaseStepAndSkipBackwards.setObjectName(_fromUtf8("actionDecreaseStepAndSkipBackwards"))
        self.actionCutSetActionSkip = QAction(MainWindow)
        self.actionCutSetActionSkip.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/cut_red.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCutSetActionSkip.setIcon(icon9)
        self.actionCutSetActionSkip.setIconVisibleInMenu(True)
        self.actionCutSetActionSkip.setObjectName(_fromUtf8("actionCutSetActionSkip"))
        self.actionCutSetActionMute = QAction(MainWindow)
        self.actionCutSetActionMute.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sound_mute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCutSetActionMute.setIcon(icon10)
        self.actionCutSetActionMute.setIconVisibleInMenu(True)
        self.actionCutSetActionMute.setObjectName(_fromUtf8("actionCutSetActionMute"))
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSaveEDL)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionPlayPause)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menu_Help.addAction(self.actionAbout)
        self.menu_Go.addAction(self.actionSkipForward)
        self.menu_Go.addAction(self.actionSkipBackwards)
        self.menu_Go.addAction(self.actionDecreaseStepAndSkipForward)
        self.menu_Go.addAction(self.actionDecreaseStepAndSkipBackwards)
        self.menu_Go.addSeparator()
        self.menu_Go.addAction(self.actionIncreaseStep)
        self.menu_Go.addAction(self.actionDecreaseStep)
        self.menu_Go.addSeparator()
        self.menu_Go.addAction(self.actionNextCutBoundary)
        self.menu_Go.addAction(self.actionPreviousCutBoundary)
        self.menu_Edit.addAction(self.actionStartCut)
        self.menu_Edit.addAction(self.actionStopCut)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionDeleteCut)
        self.menu_Edit.addAction(self.actionCutSetActionSkip)
        self.menu_Edit.addAction(self.actionCutSetActionMute)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Go.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.actionPreviousCutBoundary)
        self.toolBar.addAction(self.actionSkipBackwards)
        self.toolBar.addAction(self.actionPlayPause)
        self.toolBar.addAction(self.actionSkipForward)
        self.toolBar.addAction(self.actionNextCutBoundary)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStartCut)
        self.toolBar.addAction(self.actionStopCut)
        self.toolBar.addAction(self.actionDeleteCut)
        self.toolBar.addAction(self.actionCutSetActionSkip)
        self.toolBar.addAction(self.actionCutSetActionMute)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.actionOpen.triggered.connect(MainWindow.actionFileOpen)
        self.actionSaveEDL.triggered.connect(MainWindow.actionFileSaveEDL)
        self.actionAbout.triggered.connect(MainWindow.actionHelpAbout)
        self.actionNextCutBoundary.triggered.connect(MainWindow.seekNextBoundary)
        self.actionPreviousCutBoundary.triggered.connect(MainWindow.seekPrevBoundary)
        self.actionSkipBackwards.triggered.connect(MainWindow.seekBackwards)
        self.actionSkipForward.triggered.connect(MainWindow.seekForward)
        self.actionPlayPause.triggered.connect(MainWindow.togglePlayPause)
        self.actionDeleteCut.triggered.connect(MainWindow.cutDelete)
        self.actionStartCut.triggered.connect(MainWindow.cutStart)
        self.actionStopCut.triggered.connect(MainWindow.cutStop)
        self.actionIncreaseStep.triggered.connect(MainWindow.stepUp)
        self.actionDecreaseStep.triggered.connect(MainWindow.stepDown)
        self.actionDecreaseStepAndSkipForward.triggered.connect(MainWindow.smartSeekForward)
        self.actionDecreaseStepAndSkipBackwards.triggered.connect(MainWindow.smartSeekBackwards)
        self.actionCutSetActionSkip.triggered.connect(MainWindow.cutSetActionSkip)
        self.actionCutSetActionMute.triggered.connect(MainWindow.cutSetActionMute)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QApplication.translate("MainWindow", "EDL Editor", None))
        self.menu_File.setTitle(QApplication.translate("MainWindow", "&File", None))
        self.menu_Help.setTitle(QApplication.translate("MainWindow", "&Help", None))
        self.menu_Go.setTitle(QApplication.translate("MainWindow", "&Go", None))
        self.menu_Edit.setTitle(QApplication.translate("MainWindow", "&Edit", None))
        self.actionAbout.setText(QApplication.translate("MainWindow", "&About...", None))
        self.actionOpen.setText(QApplication.translate("MainWindow", "&Open movie...", None))
        self.actionOpen.setShortcut(QApplication.translate("MainWindow", "Ctrl+O", None))
        self.actionSaveEDL.setText(QApplication.translate("MainWindow", "&Save EDL", None))
        self.actionSaveEDL.setShortcut(QApplication.translate("MainWindow", "Ctrl+S", None))
        self.actionQuit.setText(QApplication.translate("MainWindow", "&Quit", None))
        self.actionQuit.setShortcut(QApplication.translate("MainWindow", "Ctrl+Q", None))
        self.actionSkipForward.setText(QApplication.translate("MainWindow", "Skip &Forward", None))
        self.actionSkipForward.setShortcut(QApplication.translate("MainWindow", "Right", None))
        self.actionSkipBackwards.setText(QApplication.translate("MainWindow", "Skip &Backwards", None))
        self.actionSkipBackwards.setShortcut(QApplication.translate("MainWindow", "Left", None))
        self.actionPreviousCutBoundary.setText(QApplication.translate("MainWindow", "&Previous Cut Boundary", None))
        self.actionPreviousCutBoundary.setShortcut(QApplication.translate("MainWindow", "Alt+Left", None))
        self.actionNextCutBoundary.setText(QApplication.translate("MainWindow", "&Next Cut Boundary", None))
        self.actionNextCutBoundary.setShortcut(QApplication.translate("MainWindow", "Alt+Right", None))
        self.actionPlayPause.setText(QApplication.translate("MainWindow", "&Play/Pause", None))
        self.actionPlayPause.setShortcut(QApplication.translate("MainWindow", "Ctrl+Space", None))
        self.actionStartCut.setText(QApplication.translate("MainWindow", "&Start cut", None))
        self.actionStartCut.setShortcut(QApplication.translate("MainWindow", "[", None))
        self.actionStopCut.setText(QApplication.translate("MainWindow", "S&top cut", None))
        self.actionStopCut.setShortcut(QApplication.translate("MainWindow", "]", None))
        self.actionDeleteCut.setText(QApplication.translate("MainWindow", "&Delete current cut", None))
        self.actionDeleteCut.setShortcut(QApplication.translate("MainWindow", "Del", None))
        self.actionIncreaseStep.setText(QApplication.translate("MainWindow", "&Increase step", None))
        self.actionIncreaseStep.setShortcut(QApplication.translate("MainWindow", "+", None))
        self.actionDecreaseStep.setText(QApplication.translate("MainWindow", "&Decrease step", None))
        self.actionDecreaseStep.setShortcut(QApplication.translate("MainWindow", "-", None))
        self.actionDecreaseStepAndSkipForward.setText(QApplication.translate("MainWindow", "Decrease step and skip forward", None))
        self.actionDecreaseStepAndSkipForward.setShortcut(QApplication.translate("MainWindow", "Ctrl+Right", None))
        self.actionDecreaseStepAndSkipBackwards.setText(QApplication.translate("MainWindow", "Decrease step and skip backwards", None))
        self.actionDecreaseStepAndSkipBackwards.setShortcut(QApplication.translate("MainWindow", "Ctrl+Left", None))
        self.actionCutSetActionSkip.setText(QApplication.translate("MainWindow", "Set current cut action to S&kip", None))
        self.actionCutSetActionSkip.setShortcut(QApplication.translate("MainWindow", "S", None))
        self.actionCutSetActionMute.setText(QApplication.translate("MainWindow", "Set current cut action to &Mute", None))
        self.actionCutSetActionMute.setShortcut(QApplication.translate("MainWindow", "M", None))

from edlwidget import EDLWidget
from PhononClasses import VideoPlayer
import edledit_rc

if __name__ == "__main__":
    import sys
    app = QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

