# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edledit/edledit.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(714, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/edledit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.player = VideoPlayer(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.player.sizePolicy().hasHeightForWidth())
        self.player.setSizePolicy(sizePolicy)
        self.player.setMinimumSize(QtCore.QSize(320, 180))
        self.player.setBaseSize(QtCore.QSize(640, 360))
        self.player.setObjectName("player")
        self.gridLayout.addWidget(self.player, 0, 0, 1, 1)
        self.edlWidget = EDLWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edlWidget.sizePolicy().hasHeightForWidth())
        self.edlWidget.setSizePolicy(sizePolicy)
        self.edlWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.edlWidget.setAutoFillBackground(True)
        self.edlWidget.setObjectName("edlWidget")
        self.gridLayout.addWidget(self.edlWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 25))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Go = QtWidgets.QMenu(self.menubar)
        self.menu_Go.setObjectName("menu_Go")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setObjectName("menu_Edit")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(16, 16))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.BottomToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSaveEDL = QtWidgets.QAction(MainWindow)
        self.actionSaveEDL.setEnabled(False)
        self.actionSaveEDL.setObjectName("actionSaveEDL")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSkipForward = QtWidgets.QAction(MainWindow)
        self.actionSkipForward.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/control_fastforward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSkipForward.setIcon(icon1)
        self.actionSkipForward.setIconVisibleInMenu(True)
        self.actionSkipForward.setObjectName("actionSkipForward")
        self.actionSkipBackwards = QtWidgets.QAction(MainWindow)
        self.actionSkipBackwards.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/control_rewind.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSkipBackwards.setIcon(icon2)
        self.actionSkipBackwards.setIconVisibleInMenu(True)
        self.actionSkipBackwards.setObjectName("actionSkipBackwards")
        self.actionPreviousCutBoundary = QtWidgets.QAction(MainWindow)
        self.actionPreviousCutBoundary.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/control_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreviousCutBoundary.setIcon(icon3)
        self.actionPreviousCutBoundary.setIconVisibleInMenu(True)
        self.actionPreviousCutBoundary.setObjectName("actionPreviousCutBoundary")
        self.actionNextCutBoundary = QtWidgets.QAction(MainWindow)
        self.actionNextCutBoundary.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/control_end.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNextCutBoundary.setIcon(icon4)
        self.actionNextCutBoundary.setIconVisibleInMenu(True)
        self.actionNextCutBoundary.setObjectName("actionNextCutBoundary")
        self.actionPlayPause = QtWidgets.QAction(MainWindow)
        self.actionPlayPause.setCheckable(True)
        self.actionPlayPause.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/control_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap(":/images/control_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlayPause.setIcon(icon5)
        self.actionPlayPause.setIconVisibleInMenu(True)
        self.actionPlayPause.setObjectName("actionPlayPause")
        self.actionStartCut = QtWidgets.QAction(MainWindow)
        self.actionStartCut.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/cut_start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStartCut.setIcon(icon6)
        self.actionStartCut.setIconVisibleInMenu(True)
        self.actionStartCut.setObjectName("actionStartCut")
        self.actionStopCut = QtWidgets.QAction(MainWindow)
        self.actionStopCut.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/cut_stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStopCut.setIcon(icon7)
        self.actionStopCut.setIconVisibleInMenu(True)
        self.actionStopCut.setObjectName("actionStopCut")
        self.actionDeleteCut = QtWidgets.QAction(MainWindow)
        self.actionDeleteCut.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteCut.setIcon(icon8)
        self.actionDeleteCut.setIconVisibleInMenu(True)
        self.actionDeleteCut.setObjectName("actionDeleteCut")
        self.actionIncreaseStep = QtWidgets.QAction(MainWindow)
        self.actionIncreaseStep.setObjectName("actionIncreaseStep")
        self.actionDecreaseStep = QtWidgets.QAction(MainWindow)
        self.actionDecreaseStep.setObjectName("actionDecreaseStep")
        self.actionDecreaseStepAndSkipForward = QtWidgets.QAction(MainWindow)
        self.actionDecreaseStepAndSkipForward.setObjectName("actionDecreaseStepAndSkipForward")
        self.actionDecreaseStepAndSkipBackwards = QtWidgets.QAction(MainWindow)
        self.actionDecreaseStepAndSkipBackwards.setObjectName("actionDecreaseStepAndSkipBackwards")
        self.actionCutSetActionSkip = QtWidgets.QAction(MainWindow)
        self.actionCutSetActionSkip.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/cut_red.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCutSetActionSkip.setIcon(icon9)
        self.actionCutSetActionSkip.setIconVisibleInMenu(True)
        self.actionCutSetActionSkip.setObjectName("actionCutSetActionSkip")
        self.actionCutSetActionMute = QtWidgets.QAction(MainWindow)
        self.actionCutSetActionMute.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/sound_mute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCutSetActionMute.setIcon(icon10)
        self.actionCutSetActionMute.setIconVisibleInMenu(True)
        self.actionCutSetActionMute.setObjectName("actionCutSetActionMute")
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSaveEDL)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionPlayPause)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menu_Help.addAction(self.actionAbout)
        self.menu_Go.addAction(self.actionSkipForward)
        self.menu_Go.addAction(self.actionSkipBackwards)
        self.menu_Go.addAction(self.actionDecreaseStepAndSkipForward)
        self.menu_Go.addAction(self.actionDecreaseStepAndSkipBackwards)
        self.menu_Go.addSeparator()
        self.menu_Go.addAction(self.actionIncreaseStep)
        self.menu_Go.addAction(self.actionDecreaseStep)
        self.menu_Go.addSeparator()
        self.menu_Go.addAction(self.actionNextCutBoundary)
        self.menu_Go.addAction(self.actionPreviousCutBoundary)
        self.menu_Edit.addAction(self.actionStartCut)
        self.menu_Edit.addAction(self.actionStopCut)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.actionDeleteCut)
        self.menu_Edit.addAction(self.actionCutSetActionSkip)
        self.menu_Edit.addAction(self.actionCutSetActionMute)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_Go.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.toolBar.addAction(self.actionPreviousCutBoundary)
        self.toolBar.addAction(self.actionSkipBackwards)
        self.toolBar.addAction(self.actionPlayPause)
        self.toolBar.addAction(self.actionSkipForward)
        self.toolBar.addAction(self.actionNextCutBoundary)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStartCut)
        self.toolBar.addAction(self.actionStopCut)
        self.toolBar.addAction(self.actionDeleteCut)
        self.toolBar.addAction(self.actionCutSetActionSkip)
        self.toolBar.addAction(self.actionCutSetActionMute)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        self.actionOpen.triggered.connect(MainWindow.actionFileOpen)
        self.actionSaveEDL.triggered.connect(MainWindow.actionFileSaveEDL)
        self.actionAbout.triggered.connect(MainWindow.actionHelpAbout)
        self.actionNextCutBoundary.triggered.connect(MainWindow.seekNextBoundary)
        self.actionPreviousCutBoundary.triggered.connect(MainWindow.seekPrevBoundary)
        self.actionSkipBackwards.triggered.connect(MainWindow.seekBackwards)
        self.actionSkipForward.triggered.connect(MainWindow.seekForward)
        self.actionPlayPause.triggered.connect(MainWindow.togglePlayPause)
        self.actionDeleteCut.triggered.connect(MainWindow.cutDelete)
        self.actionStartCut.triggered.connect(MainWindow.cutStart)
        self.actionStopCut.triggered.connect(MainWindow.cutStop)
        self.actionIncreaseStep.triggered.connect(MainWindow.stepUp)
        self.actionDecreaseStep.triggered.connect(MainWindow.stepDown)
        self.actionDecreaseStepAndSkipForward.triggered.connect(MainWindow.smartSeekForward)
        self.actionDecreaseStepAndSkipBackwards.triggered.connect(MainWindow.smartSeekBackwards)
        self.actionCutSetActionSkip.triggered.connect(MainWindow.cutSetActionSkip)
        self.actionCutSetActionMute.triggered.connect(MainWindow.cutSetActionMute)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EDL Editor"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_Go.setTitle(_translate("MainWindow", "&Go"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.actionAbout.setText(_translate("MainWindow", "&About..."))
        self.actionOpen.setText(_translate("MainWindow", "&Open movie..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSaveEDL.setText(_translate("MainWindow", "&Save EDL"))
        self.actionSaveEDL.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionSkipForward.setText(_translate("MainWindow", "Skip &Forward"))
        self.actionSkipForward.setShortcut(_translate("MainWindow", "Right"))
        self.actionSkipBackwards.setText(_translate("MainWindow", "Skip &Backwards"))
        self.actionSkipBackwards.setShortcut(_translate("MainWindow", "Left"))
        self.actionPreviousCutBoundary.setText(_translate("MainWindow", "&Previous Cut Boundary"))
        self.actionPreviousCutBoundary.setShortcut(_translate("MainWindow", "Alt+Left"))
        self.actionNextCutBoundary.setText(_translate("MainWindow", "&Next Cut Boundary"))
        self.actionNextCutBoundary.setShortcut(_translate("MainWindow", "Alt+Right"))
        self.actionPlayPause.setText(_translate("MainWindow", "&Play/Pause"))
        self.actionPlayPause.setShortcut(_translate("MainWindow", "Ctrl+Space"))
        self.actionStartCut.setText(_translate("MainWindow", "&Start cut"))
        self.actionStartCut.setShortcut(_translate("MainWindow", "["))
        self.actionStopCut.setText(_translate("MainWindow", "S&top cut"))
        self.actionStopCut.setShortcut(_translate("MainWindow", "]"))
        self.actionDeleteCut.setText(_translate("MainWindow", "&Delete current cut"))
        self.actionDeleteCut.setShortcut(_translate("MainWindow", "Del"))
        self.actionIncreaseStep.setText(_translate("MainWindow", "&Increase step"))
        self.actionIncreaseStep.setShortcut(_translate("MainWindow", "+"))
        self.actionDecreaseStep.setText(_translate("MainWindow", "&Decrease step"))
        self.actionDecreaseStep.setShortcut(_translate("MainWindow", "-"))
        self.actionDecreaseStepAndSkipForward.setText(_translate("MainWindow", "Decrease step and skip forward"))
        self.actionDecreaseStepAndSkipForward.setShortcut(_translate("MainWindow", "Ctrl+Right"))
        self.actionDecreaseStepAndSkipBackwards.setText(_translate("MainWindow", "Decrease step and skip backwards"))
        self.actionDecreaseStepAndSkipBackwards.setShortcut(_translate("MainWindow", "Ctrl+Left"))
        self.actionCutSetActionSkip.setText(_translate("MainWindow", "Set current cut action to S&kip"))
        self.actionCutSetActionSkip.setShortcut(_translate("MainWindow", "S"))
        self.actionCutSetActionMute.setText(_translate("MainWindow", "Set current cut action to &Mute"))
        self.actionCutSetActionMute.setShortcut(_translate("MainWindow", "M"))

from PhononClasses import VideoPlayer
from edlwidget import EDLWidget
import edledit_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

